spring:
      eureka:
           client:
            serviceUrl:
                  defaultZone: http://localhost:8761/eureka
                  instance:
                  preferIpAddress: true
      application:
             name: HRMS-SERVICE
Server:
      port: 8084
feign:
   okhttp:
      enabled: true
      